---
- name: Installing s/w
  hosts: webserver
  tasks:
   - name: Install s/w
     apt:
      name: "{{item.a}}" 
      state: "{{item.b}}"
      update_cache: "{{item.c}}"
     with_items:  
      - {a: tree,b: absent,c: no}
      - {a: apache2,b: absent,c: no}
      - {a: tomcat8,b: absent,c: yes}
      

...
